## **My name is Ashley Raber and this is my *Likes Report***
## *The date this assignment is due is the 23rd*

## the creator of this data is me and META while this data is all information that I have put into it by my actions on the app META saves it.

## This data was created for targeted content and marketing so they can give me ads of thingsi may be interested in.

## This data is reliable because it is 100% my own information in there its onoene elses and its just how i interact within the app

## In what ways may this data be unreliable? this data is unreliable because it's not very tidy and hard to look through. While the files of comemnts vs likes are seperate the individual files are hard to sort through. There my be a limit of what all I can put on there and if there is deleted data it might not show up.

In [10]:
import json
import pandas as pd

with open('liked_posts.json' , 'r') as f:
    data=json.load(f)

data[0]

{'timestamp': 1789563162,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/reel/DdVV3RzRiR4/',
   'href': 'https://www.instagram.com/reel/DdVV3RzRiR4/'},
  {'label': 'Caption',
   'value': 'Theyâ\x80\x99re honestly a vibe.\nâ\x80¢\nâ\x80¢\n#bernesemountaindog #daddysgirl #girldad #lazydog #bernerpuppy'},
  {'label': 'Title', 'value': ''},
  {'dict': [{'dict': [{'label': 'Name', 'value': 'girldad'}], 'title': ''},
    {'dict': [{'label': 'Name', 'value': 'bernerpuppy'}], 'title': ''},
    {'dict': [{'label': 'Name', 'value': 'bernesemountaindog'}], 'title': ''},
    {'dict': [{'label': 'Name', 'value': 'lazydog'}], 'title': ''},
    {'dict': [{'label': 'Name', 'value': 'daddysgirl'}], 'title': ''}],
   'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': 'Larry & Lainey'},
      {'label': 'Username', 'value': 'larryandlainey'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '17997967421816855'}

In [11]:
row ={}
row['timestamp']=data[0]['timestamp']

row

{'timestamp': 1789563162}

In [12]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']
    elif item.get('title') =='Owner':
        owner_fields = item['dict'][0]['dict']
        for owner_item in owner_fields:
            row['Owner ' + owner_item['label']] =owner_item['value']
row

{'timestamp': 1789563162,
 'URL': 'https://www.instagram.com/reel/DdVV3RzRiR4/',
 'Caption': 'Theyâ\x80\x99re honestly a vibe.\nâ\x80¢\nâ\x80¢\n#bernesemountaindog #daddysgirl #girldad #lazydog #bernerpuppy',
 'Title': '',
 'Owner URL': '',
 'Owner Name': 'Larry & Lainey',
 'Owner Username': 'larryandlainey'}

In [13]:
tidy_rows=[]

for entry in data:
    row={}
    row['timestamp'] =entry['timestamp']
    
    for item in entry['label_values']:
        if 'label' in item:
            row[item['label']] = item['value']
        elif item.get('title') =='Owner':
            owner_fields = item['dict'][0]['dict']
            for owner_item in owner_fields:
                row['Owner ' + owner_item['label']] =owner_item['value']
    tidy_rows.append(row)
tidy_rows[:2]

[{'timestamp': 1789563162,
  'URL': 'https://www.instagram.com/reel/DdVV3RzRiR4/',
  'Caption': 'Theyâ\x80\x99re honestly a vibe.\nâ\x80¢\nâ\x80¢\n#bernesemountaindog #daddysgirl #girldad #lazydog #bernerpuppy',
  'Title': '',
  'Owner URL': '',
  'Owner Name': 'Larry & Lainey',
  'Owner Username': 'larryandlainey'},
 {'timestamp': 1789563099,
  'URL': 'https://www.instagram.com/reel/DdUGjPLg_Qx/',
  'Caption': 'That ad ð\x9f\x91\x8eð\x9f\x91\x8e\n\nAs a female athlete in sports who has constantly been made to question her body to the â\x80\x9cright typeâ\x80\x9d in order to fit in, itâ\x80\x99s time for this perspective to change. Women deserve to be seen for their unique qualities through talent, hard work, dedication, athleticism, and the person they are both on and off the field.\n\n#BeYou. #womeninsports #femaleathlete #baseball',
  'Title': '',
  'Owner URL': 'http://beyouofficialbrand.com',
  'Owner Name': 'Kelsie Whitmore',
  'Owner Username': 'kelsie_whitmore'}]

In [14]:
likes_df=pd.DataFrame(tidy_rows)
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1789563162,https://www.instagram.com/reel/DdVV3RzRiR4/,Theyâre honestly a vibe.\nâ¢\nâ¢\n#bernese...,,,Larry & Lainey,larryandlainey
1,1789563099,https://www.instagram.com/reel/DdUGjPLg_Qx/,That ad ðð\n\nAs a female athlete in spo...,,http://beyouofficialbrand.com,Kelsie Whitmore,kelsie_whitmore
2,1789563011,https://www.instagram.com/reel/DdVj8ThiKdo/,While our Lorax (aka Cait) was inside getting ...,,https://linktr.ee/homeofinspire,Home of Inspire,homeofinspire
3,1789528588,https://www.instagram.com/reel/DdT9oVsgVRj/,I couldnât believe how this turned out ð±\...,,https://form.typeform.com/to/m5IxBraZ,Jakob Robinson-Collymore | Menâs online coach,jakobrcfitness
4,1789528170,https://www.instagram.com/reel/DdUsTK-SwkY/,"Just smile, keep your head down, and secure th...",,https://www.amazon.com/shop/misterwagyu,Mister Wagyu | Toy Poodle,misterwagyu
5,1789528074,https://www.instagram.com/reel/DdUQGEaM0pn/,The TRUMP-VINCIBLE UNIVERSE #conquest #invinci...,,https://linktr.ee/UncleCarlConquest,Uncle Carl/Conquest,unclecarlconquest
6,1789525737,https://www.instagram.com/reel/DdAEvK0iVnc/,Apparently this is NOT my bed. ðð¶Mom sai...,,,Benny-BendecidoBenitoï¿½,bennybendecidobenito
7,1789525736,https://www.instagram.com/reel/DdStrm3NSqF/,Itâs a shower beer. #shanehollander #heatedr...,,,Sierra Spring,siiierraspring
8,1789525442,https://www.instagram.com/p/DdUrchqgVC5/,Kent Ohio! This Friday Emo Night Kent 2.0 is b...,,https://linktr.ee/allcreaturesentertainment,Emo Night Kent,emonightkent
9,1789513674,https://www.instagram.com/reel/DdUEr4Bt87g/,Going Live for 500k Followers! #live #goingliv...,,https://linktr.ee/ShepherdFarm,Sarah Alday,shepherd.farm

In [15]:
likes_df['DateTime'] =pd.to_datetime(likes_df['timestamp'], unit='s')
likes_df[['timestamp','DateTime']].head()

    timestamp            DateTime
0  1789563162 2026-09-16 12:52:42
1  1789563099 2026-09-16 12:51:39
2  1789563011 2026-09-16 12:50:11
3  1789528588 2026-09-16 03:16:28
4  1789528170 2026-09-16 03:09:30

In [29]:
likes_per_account = likes_df.groupby('Owner Username')['timestamp'].count().reset_index()
likes_per_account.columns = ['Account Username', 'Like Count']

likes_per_account = likes_per_account.sort_values(by='Like Count', ascending=False)
likes_per_account.head(10)

     Account Username  Like Count
4926        netflixuk          65
2497         gaytimes          40
1241   cfanorthcanton          35
5032          nytimes          25
4496    meghanandjack          24
4085  lillianclaireee          24
560             ashby          17
529         arikytsya          17
4899      nccsvikings          17
6092            smosh          16

# my hypothesis is that I liked more posts of people I dont follow rather than do. I think this because if i look at the likes on there and i dont think i follow any of them. And the file i chose was the following file because that will show me who i am following.I think my follwing will just show who i was follwing

In [16]:
import json

with open("following.json", "r") as file:
    following_data =json.load(file)

In [17]:
following_data.keys()

dict_keys(['relationships_following'])

In [18]:
type(following_data["relationships_following"])

list

In [19]:
following_data["relationships_following"][0]

{'title': 'shepherd.farm',
 'string_list_data': [{'href': 'https://www.instagram.com/_u/shepherd.farm',
   'timestamp': 1789513698}]}

In [20]:
following_df=pd.DataFrame(following_data["relationships_following"])

In [21]:
following_df.head(10)

                title                                   string_list_data
0       shepherd.farm  [{'href': 'https://www.instagram.com/_u/shephe...
1  rebuiltdadofficial  [{'href': 'https://www.instagram.com/_u/rebuil...
2      miatalerico101  [{'href': 'https://www.instagram.com/_u/miatal...
3    sabrinacarpenter  [{'href': 'https://www.instagram.com/_u/sabrin...
4         hckentstate  [{'href': 'https://www.instagram.com/_u/hckent...
5  lanasweet_treats18  [{'href': 'https://www.instagram.com/_u/lanasw...
6         06moliterno  [{'href': 'https://www.instagram.com/_u/06moli...
7     jangilarockland  [{'href': 'https://www.instagram.com/_u/jangil...
8              comfrt  [{'href': 'https://www.instagram.com/_u/comfrt...
9     heatedrivalryhq  [{'href': 'https://www.instagram.com/_u/heated...

In [22]:
following_df.tail(10)

                  title                                   string_list_data
810           wengerd_5  [{'href': 'https://www.instagram.com/_u/wenger...
811         zach_raber_  [{'href': 'https://www.instagram.com/_u/zach_r...
812  fiercegirl00000000  [{'href': 'https://www.instagram.com/_u/fierce...
813  katelynbrookeraber  [{'href': 'https://www.instagram.com/_u/kately...
814       jmariesmith86  [{'href': 'https://www.instagram.com/_u/jmarie...
815       meghan.turner  [{'href': 'https://www.instagram.com/_u/meghan...
816         kait.turner  [{'href': 'https://www.instagram.com/_u/kait.t...
817            zandamom  [{'href': 'https://www.instagram.com/_u/zandam...
818          ava00grace  [{'href': 'https://www.instagram.com/_u/ava00g...
819      lilly.mcclainn  [{'href': 'https://www.instagram.com/_u/lilly....

In [26]:
following_list = []
for account in following_data['relationships_following']: 
    username = account['title']
    following_list.append(username)
# Loop through each item inside the following data PLEASE NOTE i did use AI to help me.

liked_owners_list = []
for entry in liked_data:
    for item in entry['label_values']:
        if item.get('title') == 'Owner':
            owner_info = item['dict'][0]['dict']
            for field in owner_info:
                if field['label'] == 'Username':
                    # Search for the specific field labeled 'Username', Add username to my likes list
                    liked_owners_list.append(field['value'])

likes_i_follow = 0
likes_i_dont_follow = 0
# Count likes from accounts I follow vs accounts I dont follow

for username in liked_owners_list:
    if username in following_list:
        likes_i_follow = likes_i_follow + 1
    else:
        likes_i_dont_follow = likes_i_dont_follow + 1
        # Check every username from my liked posts one by one it adds one if i follow or dont follow them.

print("Total liked posts found:", len(liked_owners_list))
print("Likes from accounts I follow:", likes_i_follow)
print("Likes from accounts I DO NOT follow:", likes_i_dont_follow)

if likes_i_dont_follow > likes_i_follow:
    print("Hypothesis Correct: I like more posts from people I don't follow.")
else:
    print("Hypothesis Incorrect: I like more posts from people I follow.")

Total liked posts found: 9696
Likes from accounts I follow: 740
Likes from accounts I DO NOT follow: 8956
Hypothesis Correct: I like more posts from people I don't follow.

 **Missing Data and Algorithm Bias:** The dataset only reflects currently active likes and current following status. If an account was unliked or unfollowed before downloading the data export, it is not in the analysis. Instagram's feed algorithm heavily pushes Reels from recommended non-followed accounts, which inherently skews interaction volume toward non-followed creators.


 **Next Steps?:** A great next step would be analyzing `comments.json` and `saved.json` to see if who i engage wiht differs between friends/followed accounts versus random accounts.